name: Build Tests and Deploy Application

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
  builder-verify:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
        cache: maven
     
     - name: list Directories
       run: ls -lha

     - name: Show user
       run: whoami

     - name: Show Java Version
       run: java --version
     
     - name: Show Maven Version
       run: mvn --version  
     
     - name: Show Git Version
       run: git --version

     - name: Show Docker Version
       run: docker --version

     - name: Show docker-compose Version
       run: docker-compose --version

     - name: Build with Maven
       run: mvn -B package --file pom.xml
    
  QA-Test:
    needs: [builder-verify]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       cache: maven
       
    - name: Test Application
      run: |
       mvn clean install
       ls -lha
       curl https://viacep.com.br/ws/13033035/json/
      
  tests:
    needs: [QA-Test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       cache: maven
    
    - name: Test Application
      run: mvn clean verify

  deploy:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
       cache: maven
    
    - name: Deploy Application 
      run: |
       mvn clean install
       mvn package