name: Build Tests And Deploy Application

on:
  push:
    branches: [ master, develop]

jobs:

  setup:
   runs-on: [ubuntu-latest]
   steps:
     - uses: roles-ansible/check-ansible-ubuntu-latest-action@0.4.1
     - name: Check Ubuntu Latest
       run: apt-get update && apt-get upgrade -y
       
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  
  tests:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Test Application
      run: mvn clean verify -DskipTests=true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Application 
      run: mvn clean package
